### ISSUE TITLE
Whether  need to support both reactive socket and other protocols or not?

### ISSUE THREAD

**Issue by meijies** [viniciusccarvalho/spring-cloud-sockets#3]
I think we should support those at same time. do best to be compatible with web service and so on.

**Comment by viniciusccarvalho** [comment]
The project is not meant to be an abstraction to any remote invocation method/protocol. 
RSocket itself has different protocols it supports, TCP with netty, WebSockets and Aeron. All rely on the principle that it's async messaging passing, which is not the case with webservices for example. There are already many abstractions for HTTP/REST/JSONRPC out there.
